// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using MyBusiness.Models;
using MyBusinessAPI.Models;

namespace DataAccess.Migrations
{
    [DbContext(typeof(admin_mybusiness_enterpriseContext))]
    [Migration("20230116184443_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin_myshop")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuDivision", b =>
                {
                    b.Property<int>("MyEnterpriseBuDivisionActive")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuDivisionDeleted")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuDivisionEnterpriseId")
                        .HasColumnType("int")
                        .HasColumnName("MyEnterpriseBuDivisionEnterprise_id");

                    b.Property<int>("MyEnterpriseBuDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MyEnterpriseBuDivision_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyEnterpriseBuDivisionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true);

                    b.ToTable("MyEnterpriseBuDivision", "dbo");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuEnterprise", b =>
                {
                    b.Property<int>("MyEnterpriseBuEnterpriseActive")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuEnterpriseDeleted")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuEnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyEnterpriseBuEnterpriseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true);

                    b.ToTable("MyEnterpriseBuEnterprise", "dbo");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuLog", b =>
                {
                    b.Property<int>("MyEnterpriseBuLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("MyEnterpriseBuLogDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("MyEnterpriseBuLogDeleteFlag")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuLogDescription")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MyEnterpriseBuLogScreenNumber")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuLogUpdateType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MyEnterpriseBuLogUserId")
                        .HasColumnType("int");

                    b.HasKey("MyEnterpriseBuLogId");

                    b.HasIndex(new[] { "MyEnterpriseBuLogScreenNumber" }, "UQ__MyEnterp__FB301ED278C6CBCE")
                        .IsUnique();

                    b.ToTable("MyEnterpriseBuLog");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunction", b =>
                {
                    b.Property<int>("MyEnterpriseBuSystemFunctionsSystemFunctionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MEnterpriseBuSystemFunctionsMyLevel")
                        .HasColumnType("int")
                        .HasColumnName("mEnterpriseBuSystemFunctionsMyLevel");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsAddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MyEnterpriseBuSystemFunctionsAddedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsArabicDescription")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsBelowLevel1")
                        .HasColumnType("int");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsBelowLevel2")
                        .HasColumnType("int");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsBelowLevel3")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MyEnterpriseBuSystemFunctionsDeletedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsDeletedFlag")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsEnglishDescription")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsEnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MyEnterpriseBuSystemFunctionsFunctionType")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuSystemFunctionsHasChild")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsIcon")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MyEnterpriseBuSystemFunctionsIsActive")
                        .HasColumnType("int");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsNotesId")
                        .HasColumnType("int");

                    b.Property<int>("MyEnterpriseBuSystemFunctionsSerialInMenu")
                        .HasColumnType("int");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsStatusColorId")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVer2012Link")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVer2017Link")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVer2020Link")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVer2023Link")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVerHtmlLink")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionsVerOtherLink")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("MyEnterpriseBuSystemFunctionsSystemFunctionsId")
                        .HasName("MyPrimaryKey");

                    b.HasIndex("MyEnterpriseBuSystemFunctionsNotesId");

                    b.HasIndex("MyEnterpriseBuSystemFunctionsStatusColorId");

                    b.ToTable("MyEnterpriseBuSystemFunctions", "dbo");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionNoteLink", b =>
                {
                    b.Property<int>("MyEnterpriseBuSystemFunctionNoteLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyEnterpriseBuSystemFunctionNoteLinkLink")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MyEnterpriseBuSystemFunctionNoteLinkNote")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MyEnterpriseBuSystemFunctionNoteLinkId");

                    b.ToTable("MyEnterpriseBuSystemFunctionNoteLink");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionRemark", b =>
                {
                    b.Property<int>("MyEnterpriseBuSystemFunctionRemarksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyEnterpriseBuSystemFunctionRemarksRemark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsDeleteFlag")
                        .HasColumnType("int");

                    b.Property<int?>("MyEnterpriseBuSystemFunctionsId")
                        .HasColumnType("int");

                    b.HasKey("MyEnterpriseBuSystemFunctionRemarksId")
                        .HasName("PK__MyEnterp__BE43296F3713B1A7");

                    b.HasIndex("MyEnterpriseBuSystemFunctionsId");

                    b.ToTable("MyEnterpriseBuSystemFunctionRemarks");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionStatusColor", b =>
                {
                    b.Property<int>("MyEnterpriseBuSystemFunctionStatusColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MyEnterpriseBuSystemFunctionDeleteFlag")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuSystemFunctionStatusColorColor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MyEnterpriseBuSystemFunctionStatusColorId");

                    b.ToTable("MyEnterpriseBuSystemFunctionStatusColor");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuTablesTranslation", b =>
                {
                    b.Property<int>("MyEnterpriseBuTablesTranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MyEnterpriseBuTablesTranslationDeleteFlag")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuTablesTranslationNameAr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MyEnterpriseBuTablesTranslationNameAR");

                    b.Property<string>("MyEnterpriseBuTablesTranslationNameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MyEnterpriseBuTablesTranslationNameEN");

                    b.HasKey("MyEnterpriseBuTablesTranslationId");

                    b.ToTable("MyEnterpriseBuTablesTranslation");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuUser", b =>
                {
                    b.Property<int>("MyEnterpriseBuUsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MyEnterpriseBuUsersDeleteFlag")
                        .HasColumnType("int");

                    b.Property<string>("MyEnterpriseBuUsersPassword1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MyEnterpriseBusersUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MyEnterpriseBUsersUsername");

                    b.HasKey("MyEnterpriseBuUsersId")
                        .HasName("PK__MyEnterp__2584C69CF707909A");

                    b.ToTable("MyEnterpriseBuUsers");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunction", b =>
                {
                    b.HasOne("Models.DBModels.MyEnterpriseBuSystemFunctionNoteLink", "MyEnterpriseBuSystemFunctionsNotes")
                        .WithMany("MyEnterpriseBuSystemFunctions")
                        .HasForeignKey("MyEnterpriseBuSystemFunctionsNotesId")
                        .HasConstraintName("FK_NOTESLINKS");

                    b.HasOne("Models.DBModels.MyEnterpriseBuSystemFunctionStatusColor", "MyEnterpriseBuSystemFunctionsStatusColor")
                        .WithMany("MyEnterpriseBuSystemFunctions")
                        .HasForeignKey("MyEnterpriseBuSystemFunctionsStatusColorId")
                        .HasConstraintName("FK_STATUSCOLOR");

                    b.Navigation("MyEnterpriseBuSystemFunctionsNotes");

                    b.Navigation("MyEnterpriseBuSystemFunctionsStatusColor");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionRemark", b =>
                {
                    b.HasOne("Models.DBModels.MyEnterpriseBuSystemFunction", "MyEnterpriseBuSystemFunctions")
                        .WithMany("MyEnterpriseBuSystemFunctionRemarks")
                        .HasForeignKey("MyEnterpriseBuSystemFunctionsId")
                        .HasConstraintName("FK__MyEnterpr__MyEnt__36470DEF");

                    b.Navigation("MyEnterpriseBuSystemFunctions");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunction", b =>
                {
                    b.Navigation("MyEnterpriseBuSystemFunctionRemarks");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionNoteLink", b =>
                {
                    b.Navigation("MyEnterpriseBuSystemFunctions");
                });

            modelBuilder.Entity("Models.DBModels.MyEnterpriseBuSystemFunctionStatusColor", b =>
                {
                    b.Navigation("MyEnterpriseBuSystemFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
