// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBusinessAPI.Models;

#nullable disable

namespace DataAccess.Migrations.admin_m_gen_b_dev
{
    [DbContext(typeof(admin_m_gen_b_devContext))]
    partial class admin_m_gen_b_devContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin_m_mybusiness_b")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBusinessAPI.Models.m_gen_b__File_Path", b =>
                {
                    b.Property<int>("m_gen_b__File_Path__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("m_gen_b__File_Path__Id"));

                    b.Property<string>("m_gen_b__File_Path__Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("m_gen_b__File_Path__Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("m_gen_b__File_Path__Path")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("m_gen_b__File_Path__Unique_Code")
                        .HasColumnType("bigint");

                    b.HasKey("m_gen_b__File_Path__Id")
                        .HasName("PK__m_gen_b___B32F696C553D479C");

                    b.ToTable("m_gen_b__File_Path", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.m_gen_b__Note", b =>
                {
                    b.Property<int>("m_gen_b__Notes__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("m_gen_b__Notes__Id"));

                    b.Property<string>("m_gen_b__Notes__Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("m_gen_b__Notes__Unique_Code")
                        .HasColumnType("bigint");

                    b.HasKey("m_gen_b__Notes__Id")
                        .HasName("PK__m_gen_b___6F60285C92F4B93E");

                    b.ToTable("m_gen_b__Notes", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.m_gen_b__Unique_Code", b =>
                {
                    b.Property<long>("m_gen_b__Unique_Code__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("m_gen_b__Unique_Code__Id"));

                    b.HasKey("m_gen_b__Unique_Code__Id")
                        .HasName("PK__m_gen_b___373056B38BE1DB48");

                    b.ToTable("m_gen_b__Unique_Code", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
