// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBusinessAPI.Models;

#nullable disable

namespace DataAccess.Migrations.admin_client_setup
{
    [DbContext(typeof(admin_client_setupContext))]
    [Migration("20230408093230_client")]
    partial class client
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin_m_mybusiness_b")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Blood_Type", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Blood_Type__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Blood_Type__Id"));

                    b.Property<string>("Client_Setup_GEN__Blood_Type__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Blood_Type__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Blood_Type__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Blood_Type__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Blood_Type__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Blood_Type__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Blood_Type__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Blood_Type__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Blood_Type__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Blood_Type__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Blood_Type__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Blood_Type__Id")
                        .HasName("PK__Client_S__3F62308FA2D3DE90");

                    b.ToTable("Client_Setup_GEN__Blood_Type", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__City", b =>
                {
                    b.Property<int>("Client_Setup_GEN__City_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__City_Id"));

                    b.Property<string>("Client_Setup_GEN__City__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Client_Setup_GEN__City__City__Dlt_By")
                        .HasColumnType("int");

                    b.Property<int>("Client_Setup_GEN__City__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__City__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Client_Setup_GEN__City__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__City__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__City__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__City__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__City__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__City__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__City__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__City_Id")
                        .HasName("PK__Client_S__C31E009680069FCD");

                    b.ToTable("Client_Setup_GEN__City", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Country", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Country__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Country__Id"));

                    b.Property<string>("Client_Setup_GEN__Country__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Country__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Country__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Country__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Country__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Country__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Country__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Country__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Country__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Country__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Country__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Country__Id")
                        .HasName("PK__Client_S__BBF96D0885BB66E3");

                    b.ToTable("Client_Setup_GEN__Country", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Degree", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Degree__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Degree__Id"));

                    b.Property<string>("Client_Setup_GEN__Degree__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Degree__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Degree__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Degree__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Degree__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Degree__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Degree__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Degree__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Degree__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Degree__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Degree__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Degree__Id")
                        .HasName("PK__Client_S__AD2598562C02910B");

                    b.ToTable("Client_Setup_GEN__Degree", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Grade", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Grade__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Grade__Id"));

                    b.Property<string>("Client_Setup_GEN__Grade__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Grade__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Grade__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Grade__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Grade__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Grade__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Grade__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Grade__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Grade__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Grade__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Grade__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Grade__Id")
                        .HasName("PK__Client_S__68E6A916EC522D25");

                    b.ToTable("Client_Setup_GEN__Grade", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Language", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Language__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Language__Id"));

                    b.Property<string>("Client_Setup_GEN__Language__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Language__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Language__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Language__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Language__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Language__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Language__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Language__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Language__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Language__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Language__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Language__Id")
                        .HasName("PK__Client_S__616A9EF5150D5A17");

                    b.ToTable("Client_Setup_GEN__Language", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Military_Status", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Military_Status__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Military_Status__Id"));

                    b.Property<string>("Client_Setup_GEN__Military_Status__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Military_Status__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Military_Status__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Military_Status__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Military_Status__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Military_Status__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Military_Status__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Military_Status__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Military_Status__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Military_Status__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Military_Status__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Military_Status__Id")
                        .HasName("PK__Client_S__D71DE6420D81867A");

                    b.ToTable("Client_Setup_GEN__Military_Status", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Nationality", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Nationality__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Nationality__Id"));

                    b.Property<string>("Client_Setup_GEN__Nationality__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Nationality__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Nationality__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Nationality__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Nationality__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Nationality__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Nationality__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Nationality__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Nationality__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Nationality__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Nationality__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Nationality__Id")
                        .HasName("PK__Client_S__3D9BE15279F832A9");

                    b.ToTable("Client_Setup_GEN__Nationality", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Realign", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Realign__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Realign__Id"));

                    b.Property<string>("Client_Setup_GEN__Realign__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Realign__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Realign__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Realign__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Realign__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Realign__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Realign__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Realign__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Realign__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Realign__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Realign__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Realign__Id")
                        .HasName("PK__Client_S__70BD99FD0282C5F2");

                    b.ToTable("Client_Setup_GEN__Realign", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Relative", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Relative__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Relative__Id"));

                    b.Property<string>("Client_Setup_GEN__Relative__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Relative__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Relative__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Relative__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Relative__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Relative__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Relative__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Relative__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Relative__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Relative__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Relative__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Relative__Id")
                        .HasName("PK__Client_S__477BFDA74965F7AC");

                    b.ToTable("Client_Setup_GEN__Relative", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__Social", b =>
                {
                    b.Property<int>("Client_Setup_GEN__Social__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__Social__Id"));

                    b.Property<string>("Client_Setup_GEN__Social__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__Social__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__Social__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__Social__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Social__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__Social__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__Social__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__Social__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__Social__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__Social__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__Social__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__Social__Id")
                        .HasName("PK__Client_S__C82345A4E33ACBAA");

                    b.ToTable("Client_Setup_GEN__Social", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup_GEN__University", b =>
                {
                    b.Property<int>("Client_Setup_GEN__University__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup_GEN__University__Id"));

                    b.Property<string>("Client_Setup_GEN__University__Ar_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Client_Setup_GEN__University__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup_GEN__University__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Client_Setup_GEN__University__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__University__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Client_Setup_GEN__University__En_Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Client_Setup_GEN__University__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup_GEN__University__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup_GEN__University__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup_GEN__University__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup_GEN__University__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup_GEN__University__Id")
                        .HasName("PK__Client_S__E02E181CBA037CBA");

                    b.ToTable("Client_Setup_GEN__University", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.Client_Setup__Login_Field", b =>
                {
                    b.Property<int>("Client_Setup__Login_Fields__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Setup__Login_Fields__Id"));

                    b.Property<int>("Client_Setup__Login_Fields__Brn_Id")
                        .HasColumnType("int");

                    b.Property<string>("Client_Setup__Login_Fields__CEDB")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .IsFixedLength();

                    b.Property<int>("Client_Setup__Login_Fields__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Client_Setup__Login_Fields__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Client_Setup__Login_Fields__Cst_Id")
                        .HasColumnType("int");

                    b.Property<int>("Client_Setup__Login_Fields__Div_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Client_Setup__Login_Fields__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup__Login_Fields__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Client_Setup__Login_Fields__Ent_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Azure_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Azure_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Azure_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Azure_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Contact_Us_Display")
                        .HasColumnType("bit");

                    b.Property<bool>("Client_Setup__Login_Fields__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Forget_Password_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Local_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Local_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Local_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Local_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Logo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Remember_Me_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Server_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Server_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Server_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Server_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<bool?>("Client_Setup__Login_Fields__Is_System_Info_Display")
                        .HasColumnType("bit");

                    b.Property<int?>("Client_Setup__Login_Fields__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Client_Setup__Login_Fields__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Client_Setup__Login_Fields__Id")
                        .HasName("PK__Client_S__A44348B0D58B77F9");

                    b.ToTable("Client_Setup__Login_Fields", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
