// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBusinessAPI.Models;

#nullable disable

namespace DataAccess.Migrations.admin_m_login_b
{
    [DbContext(typeof(admin_m_login_bContext))]
    partial class admin_m_login_bContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin_m_mybusiness_b")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBusinessAPI.Models.m_login_b_Sys_Parm", b =>
                {
                    b.Property<int>("m_login_b_Sys_Parm__Prm_Id")
                        .HasColumnType("int")
                        .HasComment("m_login_b_Sys_Parm __ Parameter Number");

                    b.Property<string>("m_login_b_Sys_Parm__Ar_Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("('')")
                        .HasComment("m_login_b_Sys_Parm __ Parameter Arabic Name");

                    b.Property<string>("m_login_b_Sys_Parm__Ar_Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("('')")
                        .HasComment("m_login_b_Sys_Parm __ Parameter Arabic Note");

                    b.Property<bool>("m_login_b_Sys_Parm__Company_Prm")
                        .HasColumnType("bit")
                        .HasComment("m_login_b_Sys_Parm __ Is Parameter for company ONLY");

                    b.Property<int>("m_login_b_Sys_Parm__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("m_login_b_Sys_Parm__Crt_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('01-01-1900')");

                    b.Property<int?>("m_login_b_Sys_Parm__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b_Sys_Parm__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("m_login_b_Sys_Parm__En_Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("('')")
                        .HasComment("m_login_b_Sys_Parm __ Parameter English Name");

                    b.Property<string>("m_login_b_Sys_Parm__En_Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("('')")
                        .HasComment("m_login_b_Sys_Parm __ Parameter English Note");

                    b.Property<bool>("m_login_b_Sys_Parm__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool>("m_login_b_Sys_Parm__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b_Sys_Parm__Is_Sys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("m_login_b_Sys_Parm__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b_Sys_Parm__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("m_login_b_Sys_Parm__Prm_Id")
                        .HasName("PK__m_login___0766BDAD64F7B14F");

                    b.ToTable("m_login_b_Sys_Parm", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.m_login_b__Field", b =>
                {
                    b.Property<int>("m_login_b__Fields__Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("m_login_b__Fields__Id"));

                    b.Property<int>("m_login_b__Fields__Brn_Id")
                        .HasColumnType("int");

                    b.Property<string>("m_login_b__Fields__CEDB")
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .IsFixedLength();

                    b.Property<int>("m_login_b__Fields__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("m_login_b__Fields__Crt_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("m_login_b__Fields__Cst_Id")
                        .HasColumnType("int");

                    b.Property<int>("m_login_b__Fields__Div_Id")
                        .HasColumnType("int");

                    b.Property<int?>("m_login_b__Fields__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b__Fields__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<int>("m_login_b__Fields__Ent_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("m_login_b__Fields__Is_Act")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Azure_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Azure_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Azure_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Azure_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Contact_Us_Display")
                        .HasColumnType("bit");

                    b.Property<bool>("m_login_b__Fields__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Forget_Password_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Local_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Local_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Local_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Local_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Logo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Remember_Me_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Server_Demo_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Server_Development_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Server_Live_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Server_Training_Display")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_Sys")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Fields__Is_System_Info_Display")
                        .HasColumnType("bit");

                    b.Property<int?>("m_login_b__Fields__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b__Fields__Upd_Date")
                        .HasColumnType("datetime");

                    b.HasKey("m_login_b__Fields__Id")
                        .HasName("PK__m_login___8D694BE0D49344CC");

                    b.ToTable("m_login_b__Fields", "dbo");
                });

            modelBuilder.Entity("MyBusinessAPI.Models.m_login_b__User", b =>
                {
                    b.Property<int>("m_login_b__Users__User_Id")
                        .HasColumnType("int");

                    b.Property<string>("m_login_b__Users__Ar_Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("m_login_b__Users__Brn_Id")
                        .HasColumnType("int");

                    b.Property<string>("m_login_b__Users__CEDB")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .HasDefaultValueSql("((0))")
                        .IsFixedLength();

                    b.Property<int>("m_login_b__Users__Crt_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("m_login_b__Users__Crt_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('01-01-1900')");

                    b.Property<int>("m_login_b__Users__Cst_Id")
                        .HasColumnType("int");

                    b.Property<int>("m_login_b__Users__Div_Id")
                        .HasColumnType("int");

                    b.Property<int?>("m_login_b__Users__Dlt_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b__Users__Dlt_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("m_login_b__Users__En_Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("m_login_b__Users__Ent_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("m_login_b__Users__Is_Act")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("m_login_b__Users__Is_Dlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("m_login_b__Users__Is_Sys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("m_login_b__Users__Login_Code")
                        .HasMaxLength(21)
                        .HasColumnType("nchar(21)")
                        .IsFixedLength();

                    b.Property<string>("m_login_b__Users__Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("m_login_b__Users__Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("m_login_b__Users__Upd_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("m_login_b__Users__Upd_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("m_login_b__Users__Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("m_login_b__Users__User_Id")
                        .HasName("PK__m_login___16811EA6338F1C92");

                    b.ToTable("m_login_b__Users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
